name: Build A530F Kernel Pro
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Build Environment
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential flex gcc-aarch64-linux-gnu git libssl-dev python3 libncurses5-dev clang lld
          
      - name: Clone Kernel Source
        run: git clone --depth=1 https://github.com/Neternels/Nethunter-Kernel-Exynos7885-Q-R-S.git kernel
          
      - name: Advanced Configuration
        run: |
          cd kernel
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          # البحث عن أفضل ملف إعدادات متوفر
          CONF=$(find arch/arm64/configs/ -name "*defconfig" | grep -i "a8" | head -n 1)
          make $(basename $CONF)
          
          # تعطيل الخيارات المسببة للفشل وتفعيل ميزات النتهنتر
          scripts/config --disable LTO_CLANG
          scripts/config --disable LTO_CLANG_THIN
          scripts/config --enable USB_G_HID
          scripts/config --enable USB_CONFIGFS_F_HID
          scripts/config --enable USB_F_MASS_STORAGE
          
      - name: Pro Compilation
        run: |
          cd kernel
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          # استخدام مجمع GCC لتجنب أخطاء Clang LTO
          make -j$(nproc) KCFLAGS="-fno-lto"
          
      - name: Export Result
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-A530F-Pro
          path: kernel/arch/arm64/boot/Image.gz-dtb
