name: Build A530F Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tools
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential flex gcc-aarch64-linux-gnu git libssl-dev python3 libncurses5-dev
          
      - name: Clone Source
        run: |
          git clone --depth=1 https://github.com/Neternels/Nethunter-Kernel-Exynos7885-Q-R-S.git kernel
          
      - name: Patch and Build
        run: |
          cd kernel
          # البحث عن ملف الإعدادات الصحيح وتفعيله
          CONF=$(find arch/arm64/configs/ -name "*defconfig" | head -n 1)
          echo "Using config: $CONF"
          make $(basename $CONF)
          
          # إضافة ميزات HID
          echo "CONFIG_USB_G_HID=y" >> .config
          echo "CONFIG_USB_F_MASS_STORAGE=y" >> .config
          
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make -j$(nproc)
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-A530F
          path: kernel/arch/arm64/boot/Image.gz-dtb
