name: Build A530F Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Tools
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential flex gcc-aarch64-linux-gnu git libssl-dev python3
          
      - name: Clone Source
        run: git clone --depth=1 https://github.com/Neternels/Nethunter-Kernel-Exynos7885-Q-R-S.git kernel
          
      - name: Fix and Build
        run: |
          cd kernel
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          # البحث عن ملف الإعدادات
          CONF=$(find arch/arm64/configs/ -name "*defconfig" | grep -i "a8" | head -n 1)
          make $(basename $CONF)
          
          # تعطيل الـ LTO المسبب للخطأ وتفعيل ميزات HID
          sed -i 's/CONFIG_LTO_CLANG=y/CONFIG_LTO_NONE=y/g' .config
          echo "CONFIG_USB_G_HID=y" >> .config
          echo "CONFIG_USB_F_MASS_STORAGE=y" >> .config
          echo "CONFIG_USB_CONFIGFS_F_HID=y" >> .config
          
          # بدء التجميع
          make -j$(nproc)
          
      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-A530F-Fixed
          path: kernel/arch/arm64/boot/Image.gz-dtb
