name: Build A530F Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential flex gcc-aarch64-linux-gnu git libssl-dev python3 libncurses5-dev
          
      - name: Clone Source
        run: |
          git clone --depth=1 https://github.com/Neternels/Nethunter-Kernel-Exynos7885-Q-R-S.git kernel
          
      - name: Configure and Patch
        run: |
          cd kernel
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make a8y18lte_defconfig
          # تفعيل ميزات HID و Mass Storage
          echo "CONFIG_USB_G_HID=y" >> .config
          echo "CONFIG_USB_F_MASS_STORAGE=y" >> .config
          echo "CONFIG_USB_CONFIGFS_F_HID=y" >> .config
          
      - name: Start Compilation
        run: |
          cd kernel
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make -j$(nproc)
          
      - name: Save Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NetHunter-Kernel-A530F
          path: kernel/arch/arm64/boot/Image.gz-dtb
