name: Build A530F
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: sudo apt update && sudo apt install -y bc bison build-essential flex gcc-aarch64-linux-gnu git libssl-dev python3
      - name: Source
        run: git clone --depth=1 https://github.com/Neternels/Nethunter-Kernel-Exynos7885-Q-R-S.git kernel
      - name: Compile
        run: |
          cd kernel
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make a8y18lte_defconfig
          echo "CONFIG_USB_G_HID=y" >> .config
          echo "CONFIG_USB_F_MASS_STORAGE=y" >> .config
          make -j$(nproc)
      - name: Final
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-A530F
          path: kernel/arch/arm64/boot/Image.gz-dtb
