name: Build A530F Official Config
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential flex gcc-aarch64-linux-gnu git libssl-dev python3
          
      - name: Clone
        run: git clone --depth=1 https://github.com/Neternels/Nethunter-Kernel-Exynos7885-Q-R-S.git kernel
          
      - name: Build Official A530F
        run: |
          cd kernel
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          
          # استخدام الكود المخصص لهاتفك مباشرة
          make a8y18lte_defconfig
          
          # إيقاف الميزات المسببة للانهيار (UKSM & LTO)
          scripts/config --disable UKSM
          scripts/config --disable LTO_CLANG
          
          # تفعيل ميزات النتهنتر (HID)
          scripts/config --enable USB_G_HID
          scripts/config --enable USB_F_HID
          scripts/config --enable USB_CONFIGFS_F_HID
          
          # بناء نهائي مستقر
          yes "" | make oldconfig
          make -j$(nproc) KCFLAGS="-fno-lto -Wno-error"
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-A530F-Official
          path: kernel/arch/arm64/boot/Image.gz-dtb
